app_name: newsflow
app_title: NewsFlow
default_title: "NewsFlow : Community Filtered News"
sub_title: "Community-maintained news"
app_url: http://rubyflow.local/
rss_url: http://rubyflow.local/items.rss
meta_keywords: "news, news site"
meta_author: "NewsFlow"
body_class: newsflow

# Use these settings to enable/disable Google Analytics statistics tracking.
uses_ga: false
ga: UA-2237791-8

# Set this to true for a more fancy interface, but for the cost of page load time
uses_javascript: false

# Edit expiration default: 60 (this means that editing ends 60 minutes after last update of item)
# Set to 0 or omit to always allow editing of items by its owner
edit_expiration_in_minutes: 60

# use Textile formatting for the sidebar - using h3. for headings.
sidebar: |- 
  
  h3. What?
  
  This site is intended for news gathering, with links chosen and summarised by the community.
  
  h3. How?
  
  Enjoy the links, comment, or "make a post":/items/new of your own. You don't need to be signed in!
  
  _Note: If you're not signed in, your byline is unlinked and your links are made "nofollow" to prevent spam. You also get CAPTCHAed!_
  
  h3. Who?
  
  RubyFlow was built by "Peter Cooper":http://peterc.org/ of "Ruby Inside":http://rubyinside.com, but is ultimately a community site.